[versions]
# Kotlin
kotlin = "2.3.10"

# Android
agp = "9.0.0"
compileSdk = "36"
minSdk = "30"
activity = "1.12.3"
material = "1.13.0"

# Compose
compose = "1.10.1"
material3 = "1.10.0-alpha05"
navigation3 = "1.0.0-alpha06"

[libraries]
# Compose
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
compose-navigation3-ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "navigation3" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }

# Android
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
material = { module = "com.google.android.material:material", version.ref = "material" }


[plugins]
# Kotlin
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

# Android
android-application = { id = "com.android.application", version.ref = "agp" }
android-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }

# Compose
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }